version: '3.8'

networks:
  vietcatholicjp-network:
    name: vietcatholicjp-network
    driver: bridge

services:
  vietcatholic-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn vietcatholicjp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./backend/.env.prod
    depends_on:
      - vietcatholic-db
    networks:
      - vietcatholicjp-network
  vietcatholic-db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod.db
    networks:
      - vietcatholicjp-network
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - vietcatholic-backend
    networks:
      - vietcatholicjp-network
volumes:
  postgres_data:
  static_volume:
